# Generated by Django 4.0.2 on 2022-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
