# Generated by Django 4.0.2 on 2022-03-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0002_gradedassignment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
