# Generated by Django 4.0.2 on 2022-03-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0006_student_teacher_question_due_time_memberlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='due_time',
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MemberList',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
