# Generated by Django 4.0.2 on 2022-03-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0007_remove_question_due_time_assignment_due_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annoucement',
            name='title',
        ),
    ]
