# Generated by Django 4.0.2 on 2022-03-16 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0008_remove_annoucement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
