# Generated by Django 4.0.2 on 2022-03-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0010_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dinoquiz.activity'),
        ),
    ]
