# Generated by Django 4.0.2 on 2022-03-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0013_remove_assignment_activity_activity_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity',
        ),
        migrations.AddField(
            model_name='assignment',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitys', to='dinoquiz.activity'),
        ),
    ]
