# Generated by Django 4.0.2 on 2022-03-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0016_alter_student_email_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
