# Generated by Django 4.0.2 on 2022-03-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0017_student_username_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_status',
            field=models.BooleanField(default=True),
        ),
    ]
