# Generated by Django 4.0.2 on 2022-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0018_activity_activity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_status',
        ),
        migrations.AddField(
            model_name='assignment',
            name='activity_status',
            field=models.BooleanField(default=False),
        ),
    ]
