# Generated by Django 4.0.2 on 2022-03-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0021_classroom_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucement',
            name='owner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
