# Generated by Django 4.0.2 on 2022-03-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinoquiz', '0023_rename_owner_annoucement_ownerfirstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='activity',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
